package com.lhzkml.jasmine.core.kernel.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration

/**
 * Indexes every @JasminePlugin class into `GeneratedPluginIndex` — the
 * compile-time plugin registry that replaces manual maps. Instantiation is
 * direct (no reflection), so R8 keeps everything reachable.
 */
class PluginIndexProcessor(private val codeGenerator: CodeGenerator) : SymbolProcessor {

    // KSP runs process() once per round; the index must be emitted exactly once.
    private var emitted = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (emitted) return emptyList()
        val definitions: List<String> = resolver
            .getSymbolsWithAnnotation("com.lhzkml.jasmine.core.kernel.JasminePlugin")
            .filterIsInstance<KSClassDeclaration>()
            .map { declaration ->
                checkNotNull(declaration.qualifiedName) {
                    "@JasminePlugin on local class ${declaration.simpleName.asString()}"
                }.asString()
            }
            .sorted()
            .toList()
        val body = if (definitions.isEmpty()) ""
        else definitions.joinToString(",\n") { "            $it()" }
        val code = """
            package com.lhzkml.jasmine.plugins

            import com.lhzkml.jasmine.core.kernel.PluginDefinition

            /** Generated by core-kernel-ksp: every @JasminePlugin class, directly instantiated. */
            object GeneratedPluginIndex {
                val definitions: List<PluginDefinition> = listOf(
            $body
                )
            }
        """.trimIndent()
        codeGenerator.createNewFile(
            Dependencies(false),
            packageName = "com.lhzkml.jasmine.plugins",
            fileName = "GeneratedPluginIndex",
        ).use { it.write(code.toByteArray()) }
        emitted = true
        return emptyList()
    }
}

class PluginIndexProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        PluginIndexProcessor(environment.codeGenerator)
}
